@startuml
skinparam linetype ortho

package "TalanCDZ" {
  enum "Role" {
    ADMIN
    USER
  }



  class "User" {
    -id: Long
    -firstName: String
    -lastName: String
    -email: String
    -password: String
    -enabled: Boolean
    -role: Role

    +getAuthorities(): Collection<? extends GrantedAuthority>
    +getUsername(): String
    +isAccountNonExpired(): boolean
    +isAccountNonLocked(): boolean
    +isCredentialsNonExpired(): boolean
    +isEnabled(): boolean
  }

}
@enduml
