@startuml
skinparam linetype ortho

package "TalanCDZ" {
  enum "Role" {
    ADMIN
    USER
  }

  class "Contrat" {
    -id: Long
    -num_dossierKPS: String
    -num_CP: String
    -raison_Social: String
    -id_Tiers: String
    -num_DC: String
    -num_SDC: String
    -num_CIR: String
    -num_SIREN: String
    -ref_Collaborative: String
    -code_Produit: String
    -identifiant_de_offre_comm: String
    -chef_de_File: String
    -num_OVI: String
    -num_RUM: String
    -typeEnergie: String
    -produit_Comm: String
    -produit: String
    -phase: String
    -montant_pret: String
  }

  class Tiers {
      -id: Long
      -numero: String
      -nom: String
      -siren: String
      -ref_mandat: String
  }

  class Dossier {
      -id: Long
      -dossier_DC: String
      -numero: String
      -listSDC: String
      -n_DPS: String
      -montant_du_pres: String
  }


  class "User" {
    -id: Long
    -firstName: String
    -lastName: String
    -email: String
    -password: String
    -enabled: Boolean
    -role: Role

    +getAuthorities(): Collection<? extends GrantedAuthority>
    +getUsername(): String
    +isAccountNonExpired(): boolean
    +isAccountNonLocked(): boolean
    +isCredentialsNonExpired(): boolean
    +isEnabled(): boolean
  }

  "User" -->  "Contrat"
   "User" -->  "Tiers"
   "User" -->  "Dossier"

}
@enduml
