pipeline {
    agent any
  environment {
        MYSQL_HOST = 'mysql'
        MYSQL_PORT = '3306'
        MYSQL_DATABASE = 'tuto'
        MYSQL_USER = 'root'
        MYSQL_PASSWORD = ''
    }
    stages {
        stage('Checkout') {
            steps{
                checkout scmGit(
                    branches: [[name: 'iheb']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://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@github.com/Kurogiri-maker/pfebackend.git']])
            }
        }
        stage('Build') {
            // some block
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh "java -version"
                sh 'java -jar target/csv-0.0.1-SNAPSHOT.jar --spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE} --spring.datasource.username=${MYSQL_USER} --spring.datasource.password=${MYSQL_PASSWORD}'
            }
        }
    }
}